// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Resource struct {
	ID       int64
	ParentID sql.NullInt64
	Name     string
	Type     string
	Color    string
	Comments string
	Image    sql.NullInt64
}

type ResourceFt struct {
	Name     string
	Color    string
	Comments string
}
