// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const changeParent = `-- name: ChangeParent :exec
update resource
set parent_id = ?1
where parent_id = ?2
`

type ChangeParentParams struct {
	NewParent sql.NullInt64
	OldParent sql.NullInt64
}

func (q *Queries) ChangeParent(ctx context.Context, arg ChangeParentParams) error {
	_, err := q.db.ExecContext(ctx, changeParent, arg.NewParent, arg.OldParent)
	return err
}

const createResource = `-- name: CreateResource :one
insert into resource (parent_id, name, type, comments, image)
values (?, ?, ?, ?, ?)
returning id
`

type CreateResourceParams struct {
	ParentID sql.NullInt64
	Name     string
	Type     string
	Comments string
	Image    sql.NullInt64
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.ParentID,
		arg.Name,
		arg.Type,
		arg.Comments,
		arg.Image,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteResource = `-- name: DeleteResource :exec
delete from resource
where id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
select id, parent_id, name, type, comments, image from resource
where id = ?
`

func (q *Queries) GetResource(ctx context.Context, id int64) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Type,
		&i.Comments,
		&i.Image,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
select id, parent_id, name, type, comments, image from resource
where parent_id is ?
`

func (q *Queries) ListResources(ctx context.Context, parentID sql.NullInt64) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Type,
			&i.Comments,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeTrash = `-- name: MakeTrash :exec
insert into resource (id, name, type)
values (1, "__Trash__", "container")
`

func (q *Queries) MakeTrash(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, makeTrash)
	return err
}

const moveResources = `-- name: MoveResources :exec
update resource
set parent_id = ?1
where id in (/*SLICE:ids*/?)
`

type MoveResourcesParams struct {
	NewParent sql.NullInt64
	Ids       []int64
}

func (q *Queries) MoveResources(ctx context.Context, arg MoveResourcesParams) error {
	query := moveResources
	var queryParams []interface{}
	queryParams = append(queryParams, arg.NewParent)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateResource = `-- name: UpdateResource :exec
update resource
set
	name = ?,
	type = ?,
	comments = ?
where id = ?
`

type UpdateResourceParams struct {
	Name     string
	Type     string
	Comments string
	ID       int64
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) error {
	_, err := q.db.ExecContext(ctx, updateResource,
		arg.Name,
		arg.Type,
		arg.Comments,
		arg.ID,
	)
	return err
}

const updateResourceImage = `-- name: UpdateResourceImage :exec
update resource
set image = ?
where id = ?
`

type UpdateResourceImageParams struct {
	Image sql.NullInt64
	ID    int64
}

func (q *Queries) UpdateResourceImage(ctx context.Context, arg UpdateResourceImageParams) error {
	_, err := q.db.ExecContext(ctx, updateResourceImage, arg.Image, arg.ID)
	return err
}
