// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createResource = `-- name: CreateResource :one
insert into resource (parent_id, name, type, color, comments, image)
values (?, ?, ?, ?, ?, ?)
returning id
`

type CreateResourceParams struct {
	ParentID sql.NullInt64
	Name     string
	Type     string
	Color    string
	Comments string
	Image    sql.NullInt64
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.ParentID,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.Comments,
		arg.Image,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteResource = `-- name: DeleteResource :exec
delete from resource
where id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const listResources = `-- name: ListResources :many
select id, parent_id, name, type, color, comments, image from resource
where parent_id is ?
`

func (q *Queries) ListResources(ctx context.Context, parentID sql.NullInt64) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResources, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Comments,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const makeTrash = `-- name: MakeTrash :exec
insert into resource (id, name, type)
values (1, "__Trash__", "container")
`

func (q *Queries) MakeTrash(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, makeTrash)
	return err
}

const moveResource = `-- name: MoveResource :exec
update resource
set parent_id = ?
where id = ?
`

type MoveResourceParams struct {
	ParentID sql.NullInt64
	ID       int64
}

func (q *Queries) MoveResource(ctx context.Context, arg MoveResourceParams) error {
	_, err := q.db.ExecContext(ctx, moveResource, arg.ParentID, arg.ID)
	return err
}

const updateResource = `-- name: UpdateResource :exec
update resource
set
	name = ?,
	type = ?,
	color = ?,
	comments = ?
where id = ?
`

type UpdateResourceParams struct {
	Name     string
	Type     string
	Color    string
	Comments string
	ID       int64
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) error {
	_, err := q.db.ExecContext(ctx, updateResource,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.Comments,
		arg.ID,
	)
	return err
}

const updateResourceImage = `-- name: UpdateResourceImage :exec
update resource
set image = ?
where id = ?
`

type UpdateResourceImageParams struct {
	Image sql.NullInt64
	ID    int64
}

func (q *Queries) UpdateResourceImage(ctx context.Context, arg UpdateResourceImageParams) error {
	_, err := q.db.ExecContext(ctx, updateResourceImage, arg.Image, arg.ID)
	return err
}
